# Generated by Django 2.1.5 on 2019-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190129_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=2),
        ),
    ]
