# Generated by Django 2.1.5 on 2019-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190129_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
