# Generated by Django 2.1.5 on 2019-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190129_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(default='album', upload_to='images/'),
        ),
    ]
