# Generated by Django 2.1.5 on 2019-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(default='album_logos/', upload_to='images'),
        ),
    ]
