# Generated by Django 2.1.5 on 2019-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20190129_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(blank=True, null=True, upload_to='Pic_folder/%Y/%m/%d/'),
        ),
    ]
