# Generated by Django 2.1.5 on 2019-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190130_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
