# Generated by Django 2.1.5 on 2019-01-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20190130_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
