# Generated by Django 2.1.5 on 2019-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20190131_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/ '),
        ),
    ]
