# Generated by Django 2.1.5 on 2019-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20190131_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='img_up',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
