# Generated by Django 2.1.5 on 2019-02-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20190201_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
