# Generated by Django 2.1.5 on 2019-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20190201_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='img_up',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
