# Generated by Django 2.1.5 on 2019-02-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20190204_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodels',
            old_name='usename',
            new_name='username',
        ),
    ]
