# Generated by Django 2.1.5 on 2019-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20190204_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_qualification', models.CharField(max_length=20)),
                ('emp_address', models.CharField(max_length=250)),
            ],
        ),
    ]
