# Generated by Django 2.1.5 on 2019-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_auto_20190207_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='employe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
