# Generated by Django 2.1.5 on 2019-02-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_employemodel_item_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='item_select',
            field=models.CharField(choices=[('1', 'Not relevant'), ('2', 'Review'), ('3', 'Maybe relevant'), ('4', 'Relevant'), ('5', 'Leading candidate')], max_length=50, null=True),
        ),
    ]
