# Generated by Django 2.1.5 on 2019-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_auto_20190213_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='item_select',
            field=models.CharField(choices=[('1', 'Not relevant'), ('2', 'Review'), ('3', 'Maybe relevant'), ('4', 'Relevant'), ('5', 'Leading candidate')], default='dsjf', max_length=50),
        ),
    ]
