# Generated by Django 2.1.5 on 2019-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_auto_20190213_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='item_select',
            field=models.CharField(choices=[('"Not relevant"', '1'), ('Review', '2'), ('Maybe relevant', '3'), ('Relevant', '4'), ('Leading candidate', '5')], default='dsjf', max_length=50),
        ),
    ]
